
baseURL: https://new-mentat.github.io
languageCode: en-us
title: New Mentat 
theme: mini
paginate: 3

markup:
  defaultMarkdownHandler: blackfriday

permalinks:
  posts: /posts/:title/

# googleAnalytics: UA-123-45

params:
  author: New Mentat 
  enableRSS: true
  enableComments: true
  # enableGoogleAnalytics: true
